name: Fluvius to Opinum Custom Range Update Job

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true
        type: string
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: true
        type: string

jobs:
  fluvius_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          FLUVIUS_CLIENT_ID: ${{ secrets.FLUVIUS_CLIENT_ID }}
          FLUVIUS_TENANT_ID: ${{ secrets.FLUVIUS_TENANT_ID }}
          FLUVIUS_CERT_THUMBPRINT: ${{ secrets.FLUVIUS_CERT_THUMBPRINT }}
          OPINUM_CLIENT_SECRET: ${{ secrets.OPINUM_CLIENT_SECRET }}
          OPINUM_USERNAME: ${{ secrets.OPINUM_USERNAME }}
          OPINUM_PASSWORD: ${{ secrets.OPINUM_PASSWORD }}
        run: |
          python custom_range_update.py ${{ github.event.inputs.start_date }} ${{ github.event.inputs.end_date }}
